/*
THIS IS A GENERATED/BUNDLED FILE FOR OBSIDIAN.
Edit src/*.ts during development, then run npm run build.
*/

const {
  ItemView,
  MarkdownRenderer,
  MarkdownView,
  Notice,
  Plugin,
  PluginSettingTab,
  requestUrl,
  Setting,
  TFile
} = require("obsidian");

const VIEW_TYPE_AI_READING_COMPANION = "ai-reading-companion-view";
const READABLE_TEXT_EXTENSIONS = new Set(["md", "txt", "csv", "json", "yaml", "yml", "html", "css", "js", "ts"]);

const DEFAULT_SETTINGS = {
  apiKey: "",
  baseUrl: "https://api.openai.com/v1",
  model: "gpt-4o-mini",
  defaultLanguage: "中文",
  replyLength: "medium",
  maxContextChars: 12000
};

const ACTION_INSTRUCTIONS = {
  free: "回应用户的自由提问。请结合选中文本在全文中的位置和作用，不要只做机械翻译。",
  explain: "解释这段内容。先说核心意思，再说它在当前文章里的作用。保持清晰、温柔、不过量。",
  simplify: "把这段讲简单一点。使用更短的句子、生活化比喻或一个小例子，不要损失关键含义。",
  stuck: "用户读不进去了。不要继续输出大量知识。先安抚，再把任务拆到很小：一句话、一个关键词或一个小问题。目标是帮用户重新进入阅读状态。",
  respond: "回应用户的想法、困惑、评论或标注。像学习搭子一样认真回应，肯定合理直觉，帮用户说清楚它为什么重要，并连接回文章内容。",
  card: "生成一张 Markdown 阅读卡片。必须使用用户指定的卡片结构，内容具体，适合插入当前笔记。"
};

function buildSystemPrompt(settings) {
  const lengthGuide = {
    short: "默认回答控制在 3-5 句，必要时使用极短 bullet。",
    medium: "默认回答控制在 2-4 个短段落，避免长篇讲义。",
    long: "可以更完整，但仍要分段清楚，不要堆砌。"
  }[settings.replyLength];

  return [
    "你是 Obsidian 里的 AI 陪读搭子，不是冷冰冰的总结器，也不是说教的老师。",
    `请默认使用${settings.defaultLanguage}回复。`,
    "你的语气温柔、稳定、清晰，不催促用户高效，不批评用户读得慢，不输出鸡汤。",
    "你的目标是帮助用户读懂一点点，并愿意继续读下去。",
    "解释时要结合选中文本和当前资料上下文，说明这段在文章或资料中的作用。",
    "如果当前资料是 PDF、Office 文档、图片或第三方插件视图，可能只有选中文本和文件名，没有全文。此时不要假装看过全文，要基于选区回答，并温和提示用户可以多选一点上下文。",
    "用户读不进去时，请降低任务难度，让任务小到可以马上开始。",
    "用户提出想法时，请认真回应这个想法，而不是只给标准答案。",
    "可以适当反问一个很小的问题，引导用户自己继续思考。",
    lengthGuide
  ].join("\n");
}

function buildUserPrompt(request) {
  if (request.action === "card") {
    return [
      "请基于当前笔记、选中文本和本次对话，生成一张 Markdown 阅读卡片。",
      "",
      "格式必须是：",
      "# 今日陪读卡片",
      "",
      "## 阅读材料",
      request.fileName || "当前文件",
      "",
      "## 我读到的位置",
      "根据选中文本或当前段落描述",
      "",
      "## 我关注的重点",
      "- ...",
      "",
      "## 我今天理解到",
      "- ...",
      "",
      "## 我还没理解",
      "- ...",
      "",
      "## AI 给我的一句提醒",
      "...",
      "",
      "当前文件名：",
      request.fileName,
      "",
      "当前笔记上下文：",
      request.noteContext,
      "",
      "选中文本：",
      request.selectedText,
      "",
      "本次对话：",
      request.conversationMarkdown || "暂无对话"
    ].join("\n");
  }

  return [
    `任务类型：${request.action}`,
    `任务说明：${ACTION_INSTRUCTIONS[request.action]}`,
    "",
    "当前文件名：",
    request.fileName,
    "",
    "当前笔记上下文：",
    request.noteContext,
    "",
    "用户选中的文本：",
    request.selectedText,
    "",
    "用户输入：",
    request.userInput || "无额外输入",
    "",
    "请直接给出陪读式回复。"
  ].join("\n");
}

async function callCompanionApi(settings, request) {
  if (!settings.apiKey) {
    throw new Error("请先在插件设置中填写 API Key。");
  }

  const baseUrl = settings.baseUrl.replace(/\/+$/, "");
  const response = await requestUrl({
    url: `${baseUrl}/chat/completions`,
    method: "POST",
    headers: {
      Authorization: `Bearer ${settings.apiKey}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      model: settings.model,
      messages: [
        { role: "system", content: buildSystemPrompt(settings) },
        { role: "user", content: buildUserPrompt(request) }
      ],
      temperature: 0.7
    }),
    throw: false
  });

  if (response.status < 200 || response.status >= 300) {
    const detail = typeof response.text === "string" ? response.text.slice(0, 500) : "";
    throw new Error(`AI 请求失败（HTTP ${response.status}）。${detail}`);
  }

  const data = response.json;
  const content = data == null ? void 0 : data.choices == null ? void 0 : data.choices[0] == null ? void 0 : data.choices[0].message == null ? void 0 : data.choices[0].message.content;
  if (!content || typeof content !== "string") {
    throw new Error("AI 返回内容为空，请检查模型名称或 API 兼容性。");
  }

  return content.trim();
}

class AIReadingCompanionSettingTab extends PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "AI 陪读搭子设置" });

    new Setting(containerEl)
      .setName("API Key")
      .setDesc("用于 OpenAI-compatible Chat Completions API。不会写入代码，只保存在 Obsidian 插件数据里。")
      .addText((text) => {
        text.inputEl.type = "password";
        text
          .setPlaceholder("sk-...")
          .setValue(this.plugin.settings.apiKey)
          .onChange(async (value) => {
            this.plugin.settings.apiKey = value.trim();
            await this.plugin.saveSettings();
          });
      });

    new Setting(containerEl)
      .setName("Base URL")
      .setDesc("例如 https://api.openai.com/v1，或其他兼容 OpenAI 格式的服务地址。")
      .addText((text) => text
        .setPlaceholder("https://api.openai.com/v1")
        .setValue(this.plugin.settings.baseUrl)
        .onChange(async (value) => {
          this.plugin.settings.baseUrl = value.trim() || DEFAULT_SETTINGS.baseUrl;
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("Model Name")
      .setDesc("例如 gpt-4o-mini、gpt-4.1-mini，或你的兼容服务提供的模型名。")
      .addText((text) => text
        .setPlaceholder("gpt-4o-mini")
        .setValue(this.plugin.settings.model)
        .onChange(async (value) => {
          this.plugin.settings.model = value.trim() || DEFAULT_SETTINGS.model;
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("默认语言")
      .setDesc("AI 回复优先使用的语言。")
      .addText((text) => text
        .setPlaceholder("中文")
        .setValue(this.plugin.settings.defaultLanguage)
        .onChange(async (value) => {
          this.plugin.settings.defaultLanguage = value.trim() || DEFAULT_SETTINGS.defaultLanguage;
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("回复长度")
      .setDesc("控制默认回复的详细程度。")
      .addDropdown((dropdown) => dropdown
        .addOption("short", "短")
        .addOption("medium", "中")
        .addOption("long", "长")
        .setValue(this.plugin.settings.replyLength)
        .onChange(async (value) => {
          this.plugin.settings.replyLength = value;
          await this.plugin.saveSettings();
        }));

    new Setting(containerEl)
      .setName("上下文最大字符数")
      .setDesc("当前笔记太长时，会围绕选中文本截取上下文。默认 12000。")
      .addText((text) => text
        .setPlaceholder("12000")
        .setValue(String(this.plugin.settings.maxContextChars))
        .onChange(async (value) => {
          const parsed = Number.parseInt(value, 10);
          this.plugin.settings.maxContextChars = Number.isFinite(parsed) && parsed > 1000 ? parsed : DEFAULT_SETTINGS.maxContextChars;
          await this.plugin.saveSettings();
        }));
  }
}

class AIReadingCompanionView extends ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.latestCardMarkdown = "";
    this.lastSelection = "";
    this.lastFile = null;
    this.conversation = [];
  }

  getViewType() {
    return VIEW_TYPE_AI_READING_COMPANION;
  }

  getDisplayText() {
    return "AI 陪读搭子";
  }

  getIcon() {
    return "book-open-check";
  }

  async onOpen() {
    const root = this.containerEl.children[1];
    root.empty();
    root.addClass("ai-reading-companion");

    const header = root.createDiv({ cls: "ai-reading-companion__header" });
    header.createEl("h2", { text: "AI 陪读搭子", cls: "ai-reading-companion__title" });
    const refreshButton = header.createEl("button", { text: "刷新选区" });
    refreshButton.addEventListener("click", () => this.refreshSelectionPreview());

    root.createDiv({ text: "当前选中文本", cls: "ai-reading-companion__section-title" });
    this.previewEl = root.createDiv({ cls: "ai-reading-companion__preview" });

    root.createDiv({ text: "想问什么", cls: "ai-reading-companion__section-title" });
    this.inputEl = root.createEl("textarea", {
      cls: "ai-reading-companion__input",
      attr: { placeholder: "例如：这段什么意思？用产品经理视角解释。这个概念和 RAG 有什么关系？" }
    });

    const primaryRow = root.createDiv({ cls: "ai-reading-companion__button-row" });
    this.createActionButton(primaryRow, "发送", "free");
    this.createActionButton(primaryRow, "解释这段", "explain");
    this.createActionButton(primaryRow, "讲简单一点", "simplify");

    const companionRow = root.createDiv({ cls: "ai-reading-companion__button-row" });
    this.createActionButton(companionRow, "我读不进去了", "stuck");
    this.createActionButton(companionRow, "回应我的想法", "respond");
    this.createActionButton(companionRow, "生成阅读卡片", "card");

    const cardRow = root.createDiv({ cls: "ai-reading-companion__button-row" });
    this.insertCardButton = cardRow.createEl("button", { text: "插入到当前笔记末尾 / 保存卡片" });
    this.insertCardButton.disabled = true;
    this.insertCardButton.addEventListener("click", () => this.insertLatestCard());

    root.createDiv({ text: "AI 回复", cls: "ai-reading-companion__section-title" });
    this.answerEl = root.createDiv({ cls: "ai-reading-companion__answer" });
    this.statusEl = root.createDiv({ cls: "ai-reading-companion__status" });

    this.refreshSelectionPreview();
  }

  async onClose() {
    this.containerEl.empty();
  }

  createActionButton(parent, label, action) {
    const button = parent.createEl("button", { text: label });
    button.addEventListener("click", () => this.runAction(action));
  }

  refreshSelectionPreview() {
    const selectedText = this.getSelectedText();
    if (selectedText) {
      this.lastSelection = selectedText;
      this.lastFile = this.getCurrentFile();
    }
    this.previewEl.empty();

    if (!selectedText && !this.lastSelection) {
      this.previewEl.createDiv({
        text: "请先在当前笔记、PDF 或预览内容中选中一段想一起读的文字。",
        cls: "ai-reading-companion__empty"
      });
      return;
    }

    const previewText = selectedText || this.lastSelection;
    this.previewEl.setText(previewText.length > 1200 ? `${previewText.slice(0, 1200)}...` : previewText);
  }

  getMarkdownView() {
    const activeMarkdownView = this.app.workspace.getActiveViewOfType(MarkdownView);
    if (activeMarkdownView) return activeMarkdownView;

    const activeFile = this.app.workspace.getActiveFile();
    const markdownLeaves = this.app.workspace.getLeavesOfType("markdown");
    for (const leaf of markdownLeaves) {
      if (leaf.view instanceof MarkdownView && leaf.view.file === activeFile) {
        return leaf.view;
      }
    }

    return null;
  }

  getSelectedText() {
    const view = this.getMarkdownView();
    const editorSelection = view == null ? void 0 : view.editor.getSelection().trim();
    if (editorSelection) return editorSelection;
    return window.getSelection()?.toString().trim() ?? "";
  }

  getSelectionOffset() {
    const view = this.getMarkdownView();
    if (!view) return -1;
    try {
      return view.editor.posToOffset(view.editor.getCursor("from"));
    } catch (error) {
      return -1;
    }
  }

  getCurrentFile() {
    var _a;
    return (((_a = this.getMarkdownView()) == null ? void 0 : _a.file) ?? this.app.workspace.getActiveFile());
  }

  async buildCurrentContext(file, selectedText) {
    const view = this.getMarkdownView();
    if (view) {
      return this.buildNoteContext(view.editor.getValue(), selectedText, this.getSelectionOffset());
    }

    if (file && READABLE_TEXT_EXTENSIONS.has(file.extension.toLowerCase())) {
      const fileText = await this.app.vault.cachedRead(file);
      return this.buildNoteContext(fileText, selectedText, fileText.indexOf(selectedText));
    }

    const sourceName = file ? `${file.path}` : "当前 Obsidian 视图";
    return [
      `当前资料：${sourceName}`,
      "MVP 暂不自动解析 PDF、图片、Office 文档或第三方插件视图的全文。",
      "请只基于用户当前选中的文本、文件名和本次对话作答；如果上下文不足，请温和说明需要用户多选一点内容。"
    ].join("\n");
  }

  buildNoteContext(fullText, selectedText, selectionOffset) {
    const maxChars = this.plugin.settings.maxContextChars;
    if (fullText.length <= maxChars) return fullText;

    const center = selectionOffset >= 0 ? selectionOffset : fullText.indexOf(selectedText);
    if (center < 0) {
      return `${fullText.slice(0, maxChars)}\n\n[当前笔记过长，已截取前 ${maxChars} 字]`;
    }

    const half = Math.floor(maxChars / 2);
    const start = Math.max(0, center - half);
    const end = Math.min(fullText.length, center + selectedText.length + half);
    const prefix = start > 0 ? "[前文已截断]\n" : "";
    const suffix = end < fullText.length ? "\n[后文已截断]" : "";
    return `${prefix}${fullText.slice(start, end)}${suffix}`;
  }

  conversationAsMarkdown() {
    return this.conversation
      .slice(-8)
      .map((turn) => `**${turn.role === "user" ? "我" : "AI"}**：\n${turn.content}`)
      .join("\n\n");
  }

  async runAction(action) {
    this.refreshSelectionPreview();

    const file = this.getCurrentFile() ?? this.lastFile;
    const selectedText = this.lastSelection;
    const userInput = this.inputEl.value.trim();

    if (!selectedText) {
      new Notice("请先选中一段想一起读的内容。");
      return;
    }

    if (action === "respond" && !userInput) {
      new Notice("请先在输入框写下你的想法、困惑或评论。");
      return;
    }

    this.setBusy(true, "正在和 AI 陪读搭子沟通...");

    try {
      const request = {
        action,
        fileName: (file == null ? void 0 : file.basename) ?? "当前 Obsidian 视图",
        noteContext: await this.buildCurrentContext(file, selectedText),
        selectedText,
        userInput,
        conversationMarkdown: this.conversationAsMarkdown()
      };

      const userTurn = this.describeUserTurn(action, userInput);
      this.conversation.push({ role: "user", content: userTurn });

      const answer = await callCompanionApi(this.plugin.settings, request);
      this.conversation.push({ role: "assistant", content: answer });

      if (action === "card") {
        this.latestCardMarkdown = answer;
        this.insertCardButton.disabled = false;
      }

      await this.renderAnswer(answer);
      this.statusEl.setText("完成");
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      new Notice(message);
      this.statusEl.setText(message);
    } finally {
      this.setBusy(false);
    }
  }

  describeUserTurn(action, userInput) {
    const labels = {
      free: "自由提问",
      explain: "解释这段",
      simplify: "讲简单一点",
      stuck: "我读不进去了",
      respond: "回应我的想法",
      card: "生成阅读卡片"
    };
    return userInput ? `${labels[action]}：${userInput}` : labels[action];
  }

  async renderAnswer(markdown) {
    this.answerEl.empty();
    await MarkdownRenderer.render(this.app, markdown, this.answerEl, "", this);
  }

  setBusy(isBusy, status = "") {
    this.statusEl.setText(status);
    const buttons = this.containerEl.querySelectorAll("button");
    buttons.forEach((button) => {
      if (button === this.insertCardButton) {
        button.disabled = isBusy || !this.latestCardMarkdown;
        return;
      }
      button.disabled = isBusy;
    });
  }

  async insertLatestCard() {
    if (!this.latestCardMarkdown) {
      new Notice("还没有可插入的阅读卡片。");
      return;
    }

    const view = this.getMarkdownView();
    if (!view) {
      await this.saveLatestCardToReadingCards();
      new Notice("当前不是 Markdown 笔记，已保存到 Reading Cards 文件夹。");
      return;
    }

    const current = view.editor.getValue();
    const card = this.latestCardMarkdown.trim();
    view.editor.setValue(`${current.trimEnd()}\n\n---\n\n${card}\n`);
    new Notice("已插入到当前笔记末尾。");
  }

  async saveLatestCardToReadingCards() {
    const activeFile = this.getCurrentFile() ?? this.lastFile;
    const baseName = (activeFile == null ? void 0 : activeFile.basename) ?? "Obsidian 陪读";
    const safeName = baseName.replace(/[\\/:*?"<>|]/g, "-");
    const now = new Date();
    const stamp = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`;
    const folder = "Reading Cards";
    const path = `${folder}/${stamp} - ${safeName}.md`;

    if (!this.app.vault.getAbstractFileByPath(folder)) {
      await this.app.vault.createFolder(folder);
    }

    const existing = this.app.vault.getAbstractFileByPath(path);
    const content = `${this.latestCardMarkdown.trim()}\n`;
    if (existing instanceof TFile) {
      await this.app.vault.append(existing, `\n---\n\n${content}`);
    } else {
      await this.app.vault.create(path, content);
    }
  }
}

class AIReadingCompanionPlugin extends Plugin {
  async onload() {
    await this.loadSettings();

    this.registerView(
      VIEW_TYPE_AI_READING_COMPANION,
      (leaf) => new AIReadingCompanionView(leaf, this)
    );

    this.addRibbonIcon("book-open-check", "打开 AI 陪读搭子", () => {
      this.activateView();
    });

    this.addCommand({
      id: "open-ai-reading-companion",
      name: "打开 AI 陪读搭子",
      callback: () => this.activateView()
    });

    this.addSettingTab(new AIReadingCompanionSettingTab(this.app, this));

    this.registerInterval(
      window.setInterval(() => {
        const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_AI_READING_COMPANION);
        for (const leaf of leaves) {
          const view = leaf.view;
          if (view instanceof AIReadingCompanionView) {
            view.refreshSelectionPreview();
          }
        }
      }, 900)
    );
  }

  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_AI_READING_COMPANION);
  }

  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_AI_READING_COMPANION);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }

    const leaf = this.app.workspace.getRightLeaf(false);
    if (!leaf) {
      new Notice("无法打开右侧边栏。");
      return;
    }

    await leaf.setViewState({
      type: VIEW_TYPE_AI_READING_COMPANION,
      active: true
    });

    this.app.workspace.revealLeaf(leaf);
  }

  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }

  async saveSettings() {
    await this.saveData(this.settings);
  }
}

module.exports = AIReadingCompanionPlugin;
